version: '3.8'

services:
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:latest
  #   container_name: TrackingDB
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: "@tm123456"
  #   ports:
  #     - "1460:1433"
  #   networks:
  #     ptms:
  #       ipv4_address: 10.43.0.3

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: dbdashboard
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@system.vn
  #     - PGADMIN_DEFAULT_PASSWORD=admin1234
  #   restart: always
  #   ports:
  #     - '5051:80'
  #   networks:
  #       ptms:
  #         ipv4_address: 10.43.0.2

  Npsqldb:
    image: postgres:latest
    container_name: "Npgsql_Db"
    ports:
      - '5432:5432'
    restart: always
    
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@o123456
    networks:
      ptms:
        ipv4_address: 10.43.0.3

  base.api:
    build:
      context: .
      dockerfile: backend/TrackingAPIsV1/ProductTrackingAPI/Dockerfile
    ports:
      - "80:80"
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Deploy
        - ASPNETCORE_URLS=http://+:80
    networks:
      ptms:
        ipv4_address: 10.43.0.4

networks:
  ptms:
    driver: bridge
    ipam:
      config:
        - subnet: 10.43.0.0/16